apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo
  labels: 
    env: rc-env-label
spec:
  template:
    metadata:
      name: template1-name
      labels:
        env: template1-env-label
    spec:
      containers:
      - image: nginx:latest
        name: nginx-container-name
  replicas: 3